const ROLES = {
    ADMIN: 'ROLE_ADMIN',
    USER: 'ROLE_USER',
    RECEPTIONIST: 'ROLE_RECEPTIONIST',
    ACCOUNTANT: 'ROLE_ACCOUNTANT',
    HOUSEKEEPING: 'ROLE_HOUSEKEEPING',
    SERVICE: 'ROLE_SERVICE',
    HR: 'ROLE_HR',
};

export {
    ROLES,
};